name: Deploy External
on: workflow_call

env:
  OS_CLOUD: openstack
  OS_CLIENT_CONFIG_FILE: ${{ github.workspace }}/clouds.yml

jobs:
  TestDeployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Copy cloud creds to file
        run: 'echo "$CLOUD" > clouds.yml'
        shell: bash
        env:
          CLOUD: ${{ secrets.CLOUD }}
      
      - name: Print inventory vars
        run: cat environments/demo/inventory/group_vars/all/variables.yml
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true
      - name: Ensure venv
        run: ./bin/ensure-venv
        shell: bash

      - name: Ansible requirements
        id: deploy-demo-instance
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 45
          max_attempts: 3
          shell: bash
          retry_on: error
          command: |
            source ./bin/activate demo \
            && ansible-galaxy install -fr requirements.yml \
            && ansible-playbook stackhpc.azimuth_ops.provision \
            -e infra_flavor_id=5f9def81-c93f-4c1f-a521-3b810061ff6c
      
      # For debugging failed deployment
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        if: ${{ failure() && steps.deploy-demo-instance.conclusion == 'failure' }}
        # with:
          # limit debug access to certain Github ssh keys
          # limit-access-to-users: sd109 # Doesn't seem to work, still accessible with any ssh key

      - name: Destroy Azimuth
        if: ${{ always() }}
        run: source ./bin/activate demo && ansible-playbook stackhpc.azimuth_ops.destroy 